export interface CliCommandSpec {
  usage: string;
  purpose: string;
}

export const CLI_OUTPUT_CONTRACT = Object.freeze({
  schema: 'q1x.cli-output-contract.v1',
  encoding: 'json',
  valuesPerInvocation: 1,
  successStream: 'stdout',
  failureStream: 'stderr',
  successExitCode: 0,
  failureExitCode: 1,
  errorSchema: 'q1x.cli-error.v1',
});

export const CLI_COMMAND_CATALOGUE: readonly CliCommandSpec[] = [
  { usage: 'q1x help', purpose: 'Return the machine-readable command catalogue.' },
  { usage: 'q1x --home <path> init', purpose: 'Initialise/open runtime state and return status.' },
  { usage: 'q1x --home <path> status [--programme <id>]', purpose: 'Return runtime or programme status.' },
  { usage: 'q1x --home <path> doctor [--json]', purpose: 'Run local runtime, connector and desktop diagnostics.' },
  { usage: 'q1x --home <path> discover --manifest <path>', purpose: 'Run capability discovery manifests.' },
  { usage: 'q1x --home <path> limits show', purpose: 'Show effective runtime limits and weakened overrides.' },
  { usage: 'q1x --home <path> backup create --output <dir>', purpose: 'Create a verified SQLite runtime backup.' },
  { usage: 'q1x backup verify <backup-path>', purpose: 'Verify backup hashes, schema and SQLite integrity.' },
  { usage: 'q1x --home <empty-target> backup restore <backup-path>', purpose: 'Restore a verified backup into an empty runtime home.' },
  { usage: 'q1x --home <path> connectors list', purpose: 'List built-in connector profiles.' },
  { usage: 'q1x --home <path> connectors show <id>', purpose: 'Show one built-in connector profile.' },
  { usage: 'q1x --home <path> connectors add <id>', purpose: 'Add a connector to local configuration.' },
  { usage: 'q1x --home <path> connectors configure <id> [--parameter key=value] [--environment name=ENV_KEY]', purpose: 'Configure connector parameters and environment-key mappings.' },
  { usage: 'q1x --home <path> connectors test <id>', purpose: 'Run connector preflight without executing provider work.' },
  { usage: 'q1x --home <path> connectors enable <id>', purpose: 'Enable a configured connector.' },
  { usage: 'q1x --home <path> connectors disable <id>', purpose: 'Disable a configured connector.' },
  { usage: 'q1x --home <path> connectors apply <id>', purpose: 'Materialise an enabled connector into a runtime endpoint.' },
  { usage: 'q1x --home <path> capabilities put --file <json>', purpose: 'Persist a capability descriptor.' },
  { usage: 'q1x --home <path> capabilities list', purpose: 'List known capabilities.' },
  { usage: 'q1x --home <path> capabilities get <id>', purpose: 'Get one capability descriptor.' },
  { usage: 'q1x --home <path> bindings put --file <json>', purpose: 'Persist an execution binding.' },
  { usage: 'q1x --home <path> bindings list', purpose: 'List execution bindings.' },
  { usage: 'q1x --home <path> bindings get <id>', purpose: 'Get one execution binding.' },
  { usage: 'q1x --home <path> team form <programme-id> --policy <json>', purpose: 'Form a capability-routed team for ready work.' },
  { usage: 'q1x --home <path> team assignments <programme-id>', purpose: 'List programme work assignments.' },
  { usage: 'q1x --home <path> team plans <programme-id>', purpose: 'List programme team plans.' },
  { usage: 'q1x --home <path> assignment cancel <assignment-id>', purpose: 'Cancel a planned assignment durably.' },
  { usage: 'q1x --home <path> proposal validate --file <json>', purpose: 'Validate a programme proposal without applying it.' },
  { usage: 'q1x --home <path> proposal accept --file <json>', purpose: 'Accept a validated proposal with checkpoint protection.' },
  { usage: 'q1x --home <path> supervision cycle <programme-id> --policy <json>', purpose: 'Run one bounded supervision cycle.' },
  { usage: 'q1x --home <path> supervision run <programme-id> --policy <json> [--max-cycles <n>]', purpose: 'Supervise until an explicit stop condition.' },
  { usage: 'q1x --home <path> supervision cycles <programme-id> --policy <json>', purpose: 'List supervision-cycle records.' },
  { usage: 'q1x --home <path> approval request --file <json>', purpose: 'Create a fail-closed approval request.' },
  { usage: 'q1x --home <path> approval list [--programme <id>]', purpose: 'List approval records.' },
  { usage: 'q1x --home <path> approval show <id>', purpose: 'Show one approval record.' },
  { usage: 'q1x --home <path> approval decide <id> --file <json>', purpose: 'Approve or reject a pending approval.' },
  { usage: 'q1x --home <path> approval apply <id>', purpose: 'Consume an approved authorisation and unblock protected work.' },
  { usage: 'q1x --home <path> evidence record --file <json> [--programme <id>]', purpose: 'Record immutable evidence.' },
  { usage: 'q1x --home <path> evidence list [--programme <id>]', purpose: 'List evidence records.' },
  { usage: 'q1x --home <path> evidence show <id>', purpose: 'Show one evidence record.' },
  { usage: 'q1x --home <path> audit list', purpose: 'List tamper-evident audit receipts.' },
  { usage: 'q1x --home <path> audit verify', purpose: 'Verify the local audit hash chain.' },
  { usage: 'q1x --home <path> recovery reconcile [--programme <id>]', purpose: 'Reconcile interrupted assignments after restart.' },
  { usage: 'q1x --home <path> adapters list', purpose: 'List adapter manifests.' },
  { usage: 'q1x --home <path> adapters get <id>', purpose: 'Get one adapter manifest.' },
  { usage: 'q1x --home <path> adapter-endpoints put --file <json>', purpose: 'Persist an adapter endpoint.' },
  { usage: 'q1x --home <path> adapter-endpoints list', purpose: 'List adapter endpoints.' },
  { usage: 'q1x --home <path> adapter-endpoints get <id>', purpose: 'Get one adapter endpoint.' },
  { usage: 'q1x --home <path> adapter execute <endpoint-id> --file <json>', purpose: 'Execute a request through an adapter endpoint.' },
  { usage: 'q1x --home <path> adapter discover <endpoint-id>', purpose: 'Discover capabilities exposed by an adapter endpoint.' },
  { usage: 'q1x --home <path> browser-endpoints put --file <json>', purpose: 'Persist a browser endpoint.' },
  { usage: 'q1x --home <path> browser-endpoints list', purpose: 'List browser endpoints.' },
  { usage: 'q1x --home <path> browser-endpoints get <id>', purpose: 'Get one browser endpoint.' },
  { usage: 'q1x --home <path> browser run <endpoint-id> --file <json>', purpose: 'Run a browser action batch.' },
  { usage: 'q1x --home <path> browser discover <endpoint-id>', purpose: 'Register browser-control capability evidence.' },
  { usage: 'q1x --home <path> desktop-endpoints put --file <json>', purpose: 'Persist a desktop endpoint.' },
  { usage: 'q1x --home <path> desktop-endpoints list', purpose: 'List desktop endpoints.' },
  { usage: 'q1x --home <path> desktop-endpoints get <id>', purpose: 'Get one desktop endpoint.' },
  { usage: 'q1x --home <path> desktop setup-first-party [--id <id>] [--name <name>] [--output-dir <dir>]', purpose: 'Configure the first-party desktop bridge for the host OS.' },
  { usage: 'q1x --home <path> desktop run <endpoint-id> --file <json>', purpose: 'Run a desktop action batch.' },
  { usage: 'q1x --home <path> desktop discover <endpoint-id>', purpose: 'Register desktop-control capability evidence.' },
  { usage: 'q1x --home <path> endpoints put --file <json>', purpose: 'Persist a model endpoint.' },
  { usage: 'q1x --home <path> endpoints list', purpose: 'List model endpoints.' },
  { usage: 'q1x --home <path> endpoints get <id>', purpose: 'Get one model endpoint.' },
  { usage: 'q1x --home <path> model invoke --file <json>', purpose: 'Invoke a configured model endpoint.' },
  { usage: 'q1x --home <path> mission put --file <json>', purpose: 'Persist a mission.' },
  { usage: 'q1x --home <path> mission list', purpose: 'List missions.' },
  { usage: 'q1x --home <path> mission show <id>', purpose: 'Show one mission.' },
  { usage: 'q1x --home <path> programme put --file <json>', purpose: 'Persist a programme.' },
  { usage: 'q1x --home <path> programme list', purpose: 'List programmes.' },
  { usage: 'q1x --home <path> programme show <id>', purpose: 'Show one programme.' },
  { usage: 'q1x --home <path> graph put --file <json>', purpose: 'Persist a work graph.' },
  { usage: 'q1x --home <path> graph show <id>', purpose: 'Show one work graph.' },
  { usage: 'q1x --home <path> replan record --file <json>', purpose: 'Record a replan event.' },
  { usage: 'q1x --home <path> execution request --file <json>', purpose: 'Record an execution request.' },
  { usage: 'q1x --home <path> execution result --file <json>', purpose: 'Record an execution result.' },
  { usage: 'q1x --home <path> checkpoint create <programme-id> [--id <id>]', purpose: 'Create a durable programme checkpoint.' },
  { usage: 'q1x --home <path> checkpoint list [--programme <id>]', purpose: 'List checkpoints.' },
  { usage: 'q1x --home <path> checkpoint restore <id>', purpose: 'Restore a programme checkpoint.' },
];

export function getCliCommandCatalogue(): readonly CliCommandSpec[] {
  return CLI_COMMAND_CATALOGUE;
}
